deploy_url: https://metpredict.at
static_url: https://cdn.jsdelivr.net/gh/rendeirolab/metpredict-website@main/assets
template_dir: templates
content_dir: content
build_dir: docs
pages:
  index:
    name: Home
    url: /
    template: index.html
    file: index.html
  research:
    name: Research
    url: /research/
    template: research.html
    file: research/index.html
  team:
    name: Team
    url: /team/
    template: team.html
    file: team/index.html
  news:
    name: News
    url: /news/
    template: news.html
    file: news/index.html
  publications:
    name: Publications
    url: /publications/
    template: publications.html
    file: publications/index.html
  contact:
    name: Contact
    url: /contact/
    template: contact.html
    file: contact/index.html